### ISSUE TITLE
缺少依赖文件导致插件不能被扫描到

### ISSUE THREAD

**Issue by zhiyuanjun** [wang-zhibo/xinuo#2]
Could not open requirements file: [Errno 2] No such file or directory: './plugins/xinuo/requirements.txt'

**Comment by wang-zhibo** [comment]
已经添加了requirements.txt 文件   但是不知道全部全,最好看看代码里导入的库  再匹配安装一下

**Comment by zhiyuanjun** [comment]
> 已经添加了requirements.txt 文件 但是不知道全部全,最好看看代码里导入的库 再匹配安装一下

我现在已经在正常运行了，但是配置的过程中还发现一个问题题，当配置流程异常时，会走
raise self.handle_error(e, "[Xinuo] init failed, ignore ")
，但是handle_error未实现，然后异常信息就打印不出来。
是因为基类本来有，现在取消了嘛？

**Comment by wang-zhibo** [comment]
代码拉一下, 应该是缺少cryptography包,已经添加到requirements.txt,代码里简单加了 logger.error(f"[Xinuo] import error: {e}")日志

**Comment by zhiyuanjun** [comment]
好的，感谢及时响应。
