### ISSUE TITLE
gpt40无法使用

### ISSUE THREAD

**Issue by single228758** [wang-zhibo/xinuo#3]
![mmexport1707443405246](https://github.com/wang-zhibo/xinuo/assets/122099583/017d60eb-e2f6-4cd6-b083-7cd3d4521e5c)
![mmexport1707443406652](https://github.com/wang-zhibo/xinuo/assets/122099583/ce42f857-25da-4d4a-98b1-d4d87e3f84ee)
是抓包不对吗

**Comment by wang-zhibo** [comment]
这个平台收费了,你得上平台看看有相应的权限没
