### ISSUE TITLE
在启用xinuo插件时一直开启失败，日志显示这个错误该如何解决

### ISSUE THREAD

**Issue by He0607** [wang-zhibo/xinuo#4]
[ERROR][2024-02-15 17:23:42][Xinuo.py:81] - xinuo 初始化: error: 'youdao_qanything_cookies'
[ERROR][2024-02-15 17:23:42][Xinuo.py:85] - [Xinuo] init failed, ignore ，错误信息：'youdao_qanything_cookies'
[WARNING][2024-02-15 17:23:42][plugin_manager.py:148] - Failed to init XINUO, diabled. exceptions must derive from BaseException
[INFO][2024-02-15 17:23:42][wechat_channel.py:207] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
插件开启失败),

**Comment by He0607** [comment]
@wang-zhibo 求大佬帮忙解决一下

**Comment by wang-zhibo** [comment]
看看配置文件 有没有。youdao_qanything_cookies 
配置文件从config.example.json 拷贝

**Comment by He0607** [comment]
好的感谢已经解决
